### ISSUE TITLE
Create functional test for failed notifications

### ISSUE THREAD

**Issue by Christoffer-Cortes** [eiffel-community/eiffel-intelligence#342]
### Description
There are tests involving missed notification but they either mock the result or inject it into the database. It would be good if there was a test that lets the back-end actually prepare the notification.

### Motivation
There is no test that lets the back-end can prepare a missed notification.

### Exemplification
You can force an exception somehow so that a missed notification is put in the database and then check that it looks as expected.

### Benefits
More thorough testing.

**Comment by e-pettersson-ericsson** [comment]
I think this issue is very important to address. It also got me thinking of another details, which I'm not sure is outside the scope for this issue or not ... 
I noticed in the documentation https://github.com/eiffel-community/eiffel-intelligence/blob/master/wiki/markdown/query.md that it was written it is possible to retrieve failed notifications using a subscription ID. I'm not entirely sure this is possible and if it is, then we need to extend the tests also to ensure this functionality holds.

**Comment by e-pettersson-ericsson** [comment]
Also tests we have for retrieving failed notifications from the database are spread out and making them hard to find. Ideally they should be in their own package and not be so tightly coupled with e.g. testing performing queries to retrieve aggregated objects from the database.

**Comment by henning-roos** [comment]
Investigate if this already exists.
@Christoffer-Cortes

**Comment by Christoffer-Cortes** [comment]
There are now integration tests for this and I feel that is sufficient.
Scenarios are described here: https://github.com/eiffel-community/eiffel-intelligence/blob/master/src/integrationtests/resources/features/FailedNotificationIT.feature
@e-pettersson-ericsson What do you think? Can I close this?

**Comment by e-pettersson-ericsson** [comment]
@Christoffer-Cortes I believe this issue was written before we had any tests at all for failed notifications so yes, I think it can be closed.
